# Generated by Django 5.2.17 on 2026-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extension_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financement',
            name='type_financement',
            field=models.CharField(choices=[('subvention', 'Subvention'), ('credit_rotatif', 'Crédit rotatif'), ('equipement', 'Dotation en équipement'), ('fonds_de_roulement', 'Fonds de roulement')], max_length=25, verbose_name="type d'appui"),
        ),
    ]
