# Generated by Django 5.2.17 on 2026-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_financement_type_financement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='type_module',
            field=models.CharField(choices=[('technique', 'Technique métier'), ('gestion', 'Gestion'), ('commercial', 'Commercial'), ('organisationnel', 'Vie associative')], max_length=20, verbose_name='type de module'),
        ),
    ]
